### PR TITLE
Added cached http handler

### PR DESCRIPTION
**Pull request by DiddiZ**

### CODE REVIEW

**Comment by FrozenCow** [comment]
The cache doesn't yet work correctly, mostly because 'context = c.context;' does not work that way. I'll pull it in locally and do some changes to also fit my needs (maximum memory use of cache) and push it after that.

**Comment by DiddiZ** [comment]
Sure

**Comment by DiddiZ** [comment]
Btw, sry for that, i hadn't a chance to test it
But i think the structure is usable :D (and easiest for api users)

**Comment by DiddiZ** [comment]
Another thing:
Add final to handle() and clearCache()

**Pull request closed without merging**
